version: '3.8'

services:
  # BCR Service
  bcr:
    build:
      context: ./bcr
      dockerfile: Dockerfile
    env_file:
      - ./bcr/.env
    ports:
      - "8000:80"
    depends_on:
      - bcr_db
      - redis

  # User Service
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    env_file:
      - ./user/.env
    ports:
      - "8001:80"
    depends_on:
      - user_db
      - redis

  # Book Service
  book:
    build:
      context: ./book
      dockerfile: Dockerfile
    env_file:
      - ./book/.env
    ports:
      - "8002:80"
    depends_on:
      - book_db
      - redis

  # Admin Service
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    env_file:
      - ./admin/.env
    ports:
      - "8003:80"
    depends_on:
      - admin_db
      - redis

  # PostgreSQL for BCR Service
  bcr_db:
    image: postgres:13
    environment:
      POSTGRES_DB: bcr_db
      POSTGRES_USER: bcr
      POSTGRES_PASSWORD: password1111
    volumes:
      - bcr_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # PostgreSQL for User Service
  user_db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password1111
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # PostgreSQL for Book Service
  book_db:
    image: postgres:13
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: book
      POSTGRES_PASSWORD: password1111
    volumes:
      - book_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # PostgreSQL for Admin Service
  admin_db:
    image: postgres:13
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1111
    volumes:
      - admin_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  # Redis Service
  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  bcr_db_data:
  user_db_data:
  book_db_data:
  admin_db_data:
